### ISSUE TITLE
compare SSIM with tree on "breakfast_room" subsampling images

### ISSUE THREAD

**Issue by cr44d** [magdasta/golem-verificator-experiments#16]

**Comment by nieznanysprawiciel** [comment]
Decision tree:

=================================================
Rows are expected labels.
Columns are labels returned by classifier:
=================================================

           #         TRUE        FALSE    DONT_KNOW       IGNORE
        TRUE [      5867.0          0.0          0.0          0.0]
       FALSE [     24591.0     140742.0          0.0          0.0]
   DONT_KNOW [     43397.0      11203.0          0.0          0.0]
      IGNORE [      1187.0       2413.0          0.0          0.0]

=================================================
Precision:                  63.9097646033 (% of correct classifications)
Correct rejections rate:    85.1263813032 (% of incorrect images that were rejected)
False rejections rate:      0.0 (% of correct images that were falsely rejected)
% unclassified samples:     0.0 (% of samples classified as DONT_KNOW)
Correct rejections rate for blured: 71.7905405405 (dataset size: 14800)
Correct rejections rate for watermark: 96.5512130046 (dataset size: 22200)
Correct rejections rate for noise: 93.2702702703 (dataset size: 18500)
Correct rejections rate for noise_colored: 99.3621621622 (dataset size: 18500)
Correct rejections rate for noise_peak: 66.2002319289 (dataset size: 25900)
Correct rejections rate for enhancedcolor: 92.5337837838 (dataset size: 14800)
Correct rejections rate for enhancedcontrast: 99.7635135135 (dataset size: 14800)
Correct rejections rate for enhancedbrightness: 100.0 (dataset size: 14800)
Correct rejections rate for randomobjects: 88.1496881497 (dataset size: 3700)
Correct rejections rate for wavelet_denoise: 87.0810810811 (dataset size: 3700)
Correct rejections rate for channelsswitched: 99.7297297297 (dataset size: 3700)
Correct rejections rate for smoothed: 15.4054054054 (dataset size: 3700)
Correct rejections rate for sharpened: 40.4054054054 (dataset size: 3700)
Correct rejections rate for different samples: 61.5873015873 (dataset size: 6300)

**Comment by nieznanysprawiciel** [comment]
SSIM threashold 0.92:

=================================================
Rows are expected labels.
Columns are labels returned by classifier:
=================================================

# TRUE FALSE DONT_KNOW IGNORE
TRUE [ 5867.0 0.0 0.0 0.0]
FALSE [ 90973.0 74360.0 0.0 0.0]
DONT_KNOW [ 40663.0 13937.0 0.0 0.0]
IGNORE [ 203.0 3397.0 0.0 0.0]

=================================================
Precision: 34.9725370532 (% of correct classifications)
Correct rejections rate: 44.9758971288 (% of incorrect images that were rejected)
False rejections rate: 0.0 (% of correct images that were falsely rejected)
% unclassified samples: 0.0 (% of samples classified as DONT_KNOW)
Correct rejections rate for blured: 60.2702702703 (dataset size: 14800)
Correct rejections rate for watermark: 42.161173971 (dataset size: 22200)
Correct rejections rate for noise: 89.6864864865 (dataset size: 18500)
Correct rejections rate for noise_colored: 89.7243243243 (dataset size: 18500)
Correct rejections rate for noise_peak: 56.7761886355 (dataset size: 25900)
Correct rejections rate for enhancedcolor: 0.0 (dataset size: 14800)
Correct rejections rate for enhancedcontrast: 0.0 (dataset size: 14800)
Correct rejections rate for enhancedbrightness: 0.560810810811 (dataset size: 14800)
Correct rejections rate for randomobjects: 32.5363825364 (dataset size: 3700)
Correct rejections rate for wavelet_denoise: 67.8108108108 (dataset size: 3700)
Correct rejections rate for channelsswitched: 8.0 (dataset size: 3700)
Correct rejections rate for smoothed: 10.1621621622 (dataset size: 3700)
Correct rejections rate for sharpened: 30.4324324324 (dataset size: 3700)
Correct rejections rate for different samples: 63.6825396825 (dataset size: 6300)
