### ISSUE TITLE
Investigate AR's "NOT verified" cases 

### ISSUE THREAD

**Issue by magdasta** [magdasta/golem-verificator-experiments#5]
Obtain data from ARs and check what happened

**Comment by Elfoniok** [comment]
Lets first gather logs from AR on sentry, so we don't have bother etam to monitor them constantly. I will prepare a change form him to integrate with AR.

Thanks to that we will know, in real time when something was not verified, and what was the reason.

What we will not have is actual image samples. The follow up would be backing up those samples, its way more easier than searching for this afterwards.

**Comment by Elfoniok** [comment]
AT least one AR is running with custom version of verificator now:
https://github.com/golemfactory/golem-verificator/tree/ARbackup

This enables:
* logs from verification are sent to sentry
* performing backup of crops when verification fails

I think this should be divided to two tasks. So obtaining data is completed. Lets create follow up task when we have some results and close this one.

**Comment by Elfoniok** [comment]
Ok we have some data, it looks like despite all effort crops sometimes move by one pixel i random direction. I suspect that this is inherent blender problem. We can investigate this, but it will be better that for a time being we adjust our cut away to rendered crop, with trial an error of 9 possible positions. This should be quite fast, in relation to whole time spent on rendering crops.
